### ISSUE TITLE
Error when adding second todo

### ISSUE THREAD

**Issue by rmschindler** [thheller/grove-todo#1]
When I run the app (via `npx shadow-cljs watch ui`), I can add one todo, but when I attempt to add a second, two errors are emitted in the console:
"An Error occurred in todo.ui.views/ui-todo-list, it will not be rendered."
and
"Error: No protocol method IComparable.-compare defined for type number: 1".

**Comment by thheller** [comment]
Oops, fixed in master now. The Comparable impl was bad. Fixed [here](https://github.com/thheller/shadow-grove/commit/d770d17a0812f91c587c6f8e44c438edfed1ffc8).
