### ISSUE TITLE
Error when escaping from editing a todo

### ISSUE THREAD

**Issue by rmschindler** [thheller/grove-todo#2]
When I run the app (via `npx shadow-cljs watch ui`), add I create a todo, and then I double-click it to edit it, and then change it (but don't hit enter), and then hit escape, two errors are emitted in the console:
"An Error occurred in todo.ui.views/ui-todo-item, it will not be rendered."
and
"TypeError: Cannot read properties of null (reading 'insertBefore')".

**Comment by thheller** [comment]
Good catch. Guess I never actually tried to cancel an actual edit before.
